Overhauling the bootloader to be more flexible
alleyinteractive/mantle-framework pull request #541
Opened 2024-05-03 19:40 UTC by srtfisher

2024-06-11 21:54 UTC, attackant requested changes
Some things for your review.

2024-06-11 21:54 UTC, attackant commented on src/mantle/framework/bootstrap/class-load-configuration.php
> +				'config', 'configuration' => null,
Not really sure, but do any of the changes for loading and merging configuration in this file have performance considerations we should think about?

2024-06-11 21:54 UTC, attackant commented on src/mantle/framework/class-bootloader.php
> +		if ( $console && ! in_array( Contracts\Console\Kernel::class, class_implements( $console ), true ) ) {
Would a `! class_exists( $handler )` also make sense here? Or would this already be caught? Same question for `with_exception_handler` method below.

2024-06-12 20:17 UTC, srtfisher commented on src/mantle/database/class-model-service-provider.php
> +	}
Yep!

2024-06-12 20:18 UTC, merged